import React, { useState, useEffect } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../../styles/Home.module.css'

const Type = ({ type: typeFromInitialProps }) => {
  const [type, setType] = useState(typeFromInitialProps)

  return (
    <div className={styles.container}>
      <Head>
        <title>Star Wars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {type}
      </main>

      <Link href="/"><a>Back</a></Link>

      <footer className={styles.footer}>
        <a>SZ</a>
      </footer>
    </div>
  )
}

Type.getInitialProps = async ({ req, res, query }) => {
  const { type } = query

  return ({
    type: query.type
  })
}

export default Type
