import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  const types = ["films", "people", "species", "starships", "planets", "vehicles"]
  return (
    <div className={styles.container}>
      <Head>
        <title>Star Wars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <img src="https://www.logo.wine/a/logo/Star_Wars/Star_Wars-Logo.wine.svg" width="200"  alt="Star Wars logo" />
      <main className={styles.main}>
        <div>
          {
            types.map(d => {
              const as = `/cat/${d}`
              return (
                <Link href="/cat/[type]" as={as}>
                  <a style={{ padding: "20px" }}>{d.charAt(0).toUpperCase() + d.slice(1)}</a>
                </Link>
              )
            })
          }
        </div>
      </main>
      <footer className={styles.footer}>
        <a>SZ X KT</a>
      </footer>
    </div>
  )
}
