import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  const types = ["films", "people", "species"]
  return (
    <div className={styles.container}>
      <Head>
        <title>Star Wars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Star Wars</h1>
      <main className={styles.main}>
        <div>
          {
            types.map(d => {
              const as = `/cat/${d}`
              return (
                <Link href="/cat/[type]" as={as}>
                  <a style={{ padding: "20px" }}>{d.charAt(0).toUpperCase() + d.slice(1)}</a>
                </Link>
              )
            })
          }
        </div>
      </main>
      <footer className={styles.footer}>
        <a>SZ</a>
      </footer>
    </div>
  )
}
